### ISSUE TITLE
make_IHM_texte ; conflits avec master

### ISSUE THREAD

**Issue by yo55** [klejim/Projet-tuteure-AS-INFO#12]
Un petit cafouillage de ma part... Dans la pull request, j'avais pushé les correctifs demandés sans puller master auparavant (qui a changé entre temps avec nottament une redéfinition du constructeur de Network qui créé des erreurs dans mes main de test). J'avais effectué les corrections ensuite mais la pull request a été validée directement. 
Cependant tu as annulé le merge de cette request juste après alors on doit être revenu à un master fonctionnel sur le dépot.

**Comment by klejim** [comment]
Oui master est fonctionnel. J'avais en effet oublié cette redéfinition en vérifiant la pull request. Je m'en suis rendu compte en testant en local et j'allais corriger l'erreur quand j'ai réalisé qu'il y avait d'autres problèmes.

Donc cafouillages de la part de tout le monde, mais c'est assez normal après tout pour un premier usage de git et GitHub. D'ici la fin du projet on devrait mieux s'en sortir.

A première vue les conflits ne sont pas si importants cependant. En plus de la redéfinition du constructeur que tu as remarqué il y aussi un problème au niveau de `StatusWindowPowerPlant` qui récupère la puissance disponible de la centrale plutôt que celle distribuée à la sous-station (les deux diffèrent d'autant plus que `PowerPlant.activePower` a changé de sens avec mes changements). En fait il faudrait probablement utiliser la ligne plutôt que la centrale pour récupérer ces informations.

**Comment by klejim** [comment]
Réglé par #14.
