### ISSUE TITLE
Validation jalon 1 et release

### ISSUE THREAD

**Issue by klejim** [klejim/Projet-tuteure-AS-INFO#17]
J'ai créé la branche [jalon1](/klejim/Projet-tuteure-AS-INFO/tree/jalon1) pour centraliser tout ce qui doit aller dans le premier jalon. J'ai aussi corrigé les deux bugs relevés ce matin.

**Comment by yo55** [comment]
OK. Mais dans cette branche, les centrales n'ont pas l'air de vouloir démarer, leur puissance utilisée est nulle et leur état à OFF à chaque fois. C'est probablement rien mais c'est embêtant pour tester un IHM :)

**Comment by klejim** [comment]
C'est étrange, je n'ai pas ça de mon côté. En exécutant View les centrales sont initialement toutes éteintes puis démarrent à la première itération. Elles finissent par s'allumer après un certain nombre d'itérations dépendant de leur type.

Si tu n'as pas ce comportement il y a un problème quelque part.

**Comment by yo55** [comment]
OK. Moi, j'essayais à partir de la classe Test et la seule différence est qu'il y manque  myNetwork.handleErrors(myNetwork.analyze()); On verra ça à la prochaine réunion
