### ISSUE TITLE
IHM : noms incorrects pour les éléments du réseau

### ISSUE THREAD

**Issue by klejim** [klejim/Projet-tuteure-AS-INFO#18]
L'affichage actuel utilise l'attribut `id` des éléments alors qu'ils ont tous un nom accessible via l'attribut `name`. Cela donne des situations intéressantes où l'élément "centrale 1" (c'est son nom) est présenté comme la "PowerPlant 4" (son id).

**Comment by yo55** [comment]
OK. Je crois me souvenir qu'a l'époque où j'ai commencé à developper l'IHM, les noms des nodes n'étais pas utilisables. J'ai modifié ça pour utiliser getName(). Reste à voir si les noms conviennent réellement. Par exemple, on a gas 1 mais nucléaire sans numéro.

Les modifications sont enregistrées dans le dernier commit de make_userInput

**Comment by klejim** [comment]
Super je ferme dans ce cas.
